Repository Eight-Horsepeople-of-the-Graduation/core, pull requests merged in 2024-07, with the labels that each got.

#94 Update env variables docker
  docker-compose.yml
  src/interfaces/service.interface.ts
  src/prisma/migrations/20240625160640_init/migration.sql
  src/prisma/migrations/20240625174440_/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/tests/controllers/bookshelves.controller.test.ts
  src/tests/repositories/bookshelves.repository.test.ts
Labels: documentation

#95 BREAKING CHANGE: remove volume from compose file
  docker-compose.yml
Labels: enhancement

#105 Update on delete relations
  src/controllers/books.controller.ts
  src/controllers/reviews.controller.ts
  src/dtos/reviews.dto.ts
  src/prisma/migrations/20240703144440_/migration.sql
  src/prisma/migrations/20240703145432_/migration.sql
  src/prisma/schema.prisma
  src/prisma/seed/seeders/book.seeder.ts
  src/repositories/books.repository.ts
  src/repositories/reviews.repository.ts
  src/routes/books.route.ts
  src/services/reviews.service.ts
Labels: enhancement

#110 User get book by username
  src/controllers/users.controller.ts
  src/dtos/users.dto.ts
  src/prisma/migrations/20240703145432_/migration.sql
  src/prisma/migrations/20240703155721_init/migration.sql
  src/prisma/schema.prisma
  src/prisma/seed/seeders/user.seeder.ts
  src/repositories/users.repository.ts
  src/routes/users.route.ts
  src/services/users.service.ts
  src/swagger/interfaces.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
Labels: enhancement

#121 Refactor: create interfaces
  src/controllers/authors.controller.ts
  src/controllers/books.controller.ts
  src/controllers/bookshelves.controller.ts
  src/controllers/genres.controller.ts
  src/controllers/reviews.controller.ts
  src/controllers/users.controller.ts
  src/dtos/users.dto.ts
  src/interfaces/authors.interface.ts
  src/interfaces/books.interface.ts
  src/interfaces/bookshelves.interface.ts
  src/interfaces/conversations.interface.ts
  src/interfaces/genres.interface.ts
  src/interfaces/messages.interface.ts
  src/interfaces/reading-challenges.interface.ts
  src/interfaces/reviews.interface.ts
  src/interfaces/users.interface.ts
  src/repositories/authors.repository.ts
  src/repositories/books.repository.ts
  src/repositories/bookshelves.repository.ts
  src/repositories/genres.repository.ts
  src/repositories/reviews.repository.ts
  src/repositories/users.repository.ts
  src/routes/books.route.ts
  src/routes/users.route.ts
  src/services/authors.service.ts
  src/services/books.service.ts
  src/services/bookshelves.service.ts
  src/services/genres.service.ts
  src/services/reviews.service.ts
  src/services/users.service.ts
  src/swagger/authors.swagger.ts
  src/swagger/books.swagger.ts
  src/swagger/bookshelves.swagger.ts
  src/swagger/conversations.swagger.ts
  src/swagger/genres.swagger.ts
  src/swagger/interfaces.ts
  src/swagger/reading-challenges.swagger.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
Labels: refactor

#123 Add JWT authentication
  package.json
  src/app.ts
  src/config/index.ts
  src/controllers/auth.controller.ts
  src/controllers/users.controller.ts
  src/dtos/auth.dto.ts
  src/dtos/users.dto.ts
  src/loaders/express.ts
  src/prisma/migrations/20240701151851_update_user_columns/migration.sql
  src/prisma/schema.prisma
  src/repositories/users.repository.ts
  src/routes/auth.route.ts
  src/routes/users.route.ts
  src/services/auth.service.ts
  src/services/users.service.ts
  src/types/express.d.ts
  src/types/jwt-payload.interface.ts
  tsconfig.json
Labels: enhancement

#99 Add unit tests for reading challenge service layer and repository layer
  src/controllers/reading-challenges.controller.ts
  src/repositories/reading-challenges.repository.ts
  src/services/reading-challenges.service.ts
  src/tests/controllers/reading-challenges.controller.test.ts
  src/tests/repositories/reading-challenges.repository.test.ts
  src/tests/services/reading-challenges.service.test.ts
Labels: enhancement

#102 Add delete book from reading challenge api and it's corresponding unit tests
  src/controllers/reading-challenges.controller.ts
  src/dtos/reading-challenges.dto.ts
  src/prisma/migrations/20240702135723_/migration.sql
  src/prisma/seed/seed.ts
  src/repositories/reading-challenges.repository.ts
  src/routes/reading-challenges.route.ts
  src/services/reading-challenges.service.ts
  src/swagger/reading-challenges.swagger.ts
  src/swagger/swagger.json
  src/tests/controllers/reading-challenges.controller.test.ts
  src/tests/repositories/reading-challenges.repository.test.ts
Labels: enhancement

#112 Add unit tests for book service and repository layer
  src/controllers/books.controller.ts
  src/dtos/books.dto.ts
  src/dtos/search.dto.ts
  src/repositories/books.repository.ts
  src/services/books.service.ts
  src/tests/controllers/books.controller.test.ts
  src/tests/controllers/bookshelves.controller.test.ts
  src/tests/controllers/reading-challenges.controller.test.ts
  src/tests/repositories/books.repositories.test.ts
  src/tests/repositories/bookshelves.repository.test.ts
Labels: enhancement

#126 fix: fix the user interfaces
  src/controllers/auth.controller.ts
  src/controllers/users.controller.ts
  src/dtos/auth.dto.ts
  src/dtos/users.dto.ts
  src/interfaces/users.interface.ts
  src/prisma/migrations/20240702135723_/migration.sql
  src/prisma/migrations/20240703155721_init/migration.sql
  src/prisma/migrations/20240706204039_init/migration.sql
  src/repositories/users.repository.ts
  src/services/auth.service.ts
  src/services/users.service.ts
  src/swagger/auth.swagger.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
Labels: bug

#117 feat: Add prismaErrorHandlerMiddleware for handling Prisma errors
  src/app.ts
  src/middleware/prisma-error-handler.middleware.ts
  src/utils/handle-prisma-error.ts
Labels: refactor

#128 chore: Remove try/catch statements from userRepo
  src/repositories/users.repository.ts
Labels: bug

#122 Feat! : change the conversations api
  src/controllers/conversations.controller.ts
  src/dtos/conversations.dto.ts
  src/interfaces/conversations.interface.ts
  src/interfaces/messages.interface.ts
  src/middleware/error-handler.middleware.ts
  src/prisma/migrations/20240706012319_convo_unique_constraint/migration.sql
  src/prisma/schema.prisma
  src/prisma/seed/seeders/conversation.seeder.ts
  src/repositories/conversations.repository.ts
  src/routes/conversations.route.ts
  src/services/conversations.service.ts
  src/swagger/conversations.swagger.ts
  src/swagger/swagger.json
  src/utils/handle-prisma-error.ts
Labels: enhancement

#129 Add authentication middleware
  src/dtos/users.dto.ts
  src/middleware/auth.middleware.ts
  src/middleware/refresh-tokens.middleware.ts
  src/prisma/migrations/20240706204039_init/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/repositories/users.repository.ts
  src/types/user-with-refresh-token.type.ts
Labels: enhancement, users:repository, MIDDLEWARES, auth:middleware

#130 Enhance auth middleware to handle invalid tokens and missing refresh tokens
  src/controllers/auth.controller.ts
  src/middleware/auth.middleware.ts
  src/middleware/refresh-tokens.middleware.ts
  src/prisma/migrations/20240706012319_convo_unique_constraint/migration.sql
  src/prisma/migrations/20240707085425_clean_slate/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/services/auth.service.ts
Labels: enhancement, auth:service, auth:controller, MIDDLEWARES, auth:middleware

#131 Refactor controllers and services
  src/controllers/auth.controller.ts
  src/controllers/authors.controller.ts
  src/controllers/books.controller.ts
  src/controllers/bookshelves.controller.ts
  src/controllers/genres.controller.ts
  src/controllers/reading-challenges.controller.ts
  src/controllers/reviews.controller.ts
  src/controllers/users.controller.ts
  src/dtos/books.dto.ts
  src/dtos/bookshelves.dto.ts
  src/dtos/reviews.dto.ts
  src/dtos/users.dto.ts
  src/middleware/auth.middleware.ts
  src/middleware/error-handler.middleware.ts
  src/repositories/authors.repository.ts
  src/repositories/books.repository.ts
  src/repositories/bookshelves.repository.ts
  src/repositories/reading-challenges.repository.ts
  src/repositories/reviews.repository.ts
  src/repositories/users.repository.ts
  src/routes/auth.route.ts
  src/routes/authors.route.ts
  src/routes/books.route.ts
  src/routes/bookshelves.route.ts
  src/routes/genres.route.ts
  src/routes/reading-challenges.route.ts
  src/routes/reviews.route.ts
  src/routes/users.route.ts
  src/services/authors.service.ts
  src/services/books.service.ts
  src/services/bookshelves.service.ts
  src/services/genres.service.ts
  src/services/reading-challenges.service.ts
  src/services/reviews.service.ts
  src/services/users.service.ts
  src/swagger/auth.swagger.ts
  src/swagger/authors.swagger.ts
  src/swagger/books.swagger.ts
  src/swagger/bookshelves.swagger.ts
  src/swagger/conversations.swagger.ts
  src/swagger/genres.swagger.ts
  src/swagger/reading-challenges.swagger.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
  src/types/prismaClient-transaction.type.ts
  src/utils/handle-prisma-error.ts
Labels: refactor, auth:dto, auth:service, auth:controller, auth:routes, books:dto, books:repository, books:service, books:controller, books:routes, books:interfaces, auth:interfaces, bookshelves:repository, bookshelves:services, bookshelves:controller, bookshelves:dto, bookshelves:interfaces, bookshelves:routes, authors:dto, authors:repository, authors:service, authors:controller, authors:routes, authors:interfaces, conversations:dto, conversations:repository, conversations:service, conversations:controller, conversations:routes, conversations:interfaces, genres:dto, genres:repository, genres:service, genres:controller, genres:routes, genres:interfaces, reading-challenges:dto, reading-challenges:repository, reading-challenges:service, reading-challenges:controller, reading-challenges:routes, reading-challenges:interfaces, users:dto, users:repository, users:service, users:controller, users:routes, users:interfaces, reviews:dto, reviews:repository, reviews:service, reviews:controller, reviews:routes, reviews:interfaces, SWAGGER, authors:tests, DATABASE SCHEMA, MIDDLEWARES, UTILITIES, auth:middleware

#133 132 feat! : change the reading challenges
  package.json
  src/controllers/reading-challenges.controller.ts
  src/controllers/users.controller.ts
  src/dtos/reading-challenges.dto.ts
  src/interfaces/books.interface.ts
  src/interfaces/reading-challenges.interface.ts
  src/prisma/migrations/20240708030411_init/migration.sql
  src/prisma/schema.prisma
  src/prisma/seed/seeders/reading-challenge.seeder.ts
  src/repositories/reading-challenges.repository.ts
  src/routes/reading-challenges.route.ts
  src/routes/users.route.ts
  src/services/reading-challenges.service.ts
  src/services/users.service.ts
  src/swagger/reading-challenges.swagger.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
  src/utils/dates-utils.ts
Labels: reading-challenges:dto, reading-challenges:repository, reading-challenges:service, reading-challenges:controller, reading-challenges:routes, reading-challenges:interfaces, SWAGGER, reading-challengs:test, DATABASE SCHEMA

#135 Add error handling to books module
  src/modules/books/books.repository.ts
  src/modules/reading-challenges/reading-challenges.service.ts
Labels: books:repository, books:service, books:controller

#138 fix(conversations): adjust parameter order in getConversationByU…
  src/modules/conversations/conversations.service.ts
Labels: conversations:service

#144 Add-rate-limiter
  package.json
  src/app.ts
  src/loaders/middleware.loader.ts
  src/loaders/routes.loader.ts
  tsconfig.json
Labels: enhancement, MIDDLEWARES

#142 141 feat adjust error handling
  src/modules/books/books.controller.ts
  src/modules/books/books.service.ts
  src/modules/conversations/conversations.controller.ts
  src/modules/conversations/conversations.service.ts
  src/modules/reading-challenges/reading-challenges.controller.ts
  src/modules/reading-challenges/reading-challenges.service.ts
Labels: books:service, books:controller, conversations:service, conversations:controller, reading-challenges:service, reading-challenges:controller

#147 feat: Add authentication middleware to required routes
  src/modules/authors/authors.route.ts
  src/modules/books/books.route.ts
  src/modules/bookshelves/bookshelves.route.ts
  src/modules/conversations/conversations.route.ts
  src/modules/genres/genres.route.ts
  src/modules/reading-challenges/reading-challenges.route.ts
  src/modules/reviews/reviews.route.ts
  src/modules/users/users.route.ts
Labels: books:routes, bookshelves:routes, authors:routes, genres:routes, reading-challenges:routes, users:routes, reviews:routes

#153 Enhance-readme
  .env.example
  .github/assets/Logo.png
  .github/assets/arch.png
  .github/assets/readify.jpg
  readme.md
Labels: documentation

#156 152 fix fix the testing pipelines
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  package.json
  prisma/schema.prisma
  src/modules/bookshelves/bookshelves.service.ts
  src/tests/integration-tests/author.repository.test.ts
  src/tests/integration-tests/books.repository.test.ts
  src/tests/integration-tests/bookshelves.repository.test.ts
  src/tests/integration-tests/conversation.repository.test.ts
  src/tests/integration-tests/genres.repository.test.ts
  src/tests/integration-tests/reading-challenges.repository.test.ts
  src/tests/integration-tests/reviews.repository.test.ts
  src/tests/integration-tests/user.repository.test.ts
  src/tests/unit-tests/controllers/conversation.controller.test.ts
  src/tests/unit-tests/controllers/reading-challenges.controller.test.ts
  src/tests/unit-tests/services/bookshelves.service.test.ts
  src/tests/unit-tests/services/reading-challenges.service.test.ts
  src/tests/unit-tests/services/reviews.service.test.ts
Labels: reviews:tests, authors:tests, books:tests, bookshelves:tests, users:tests, conversations:tests

#158 Adjust user seeding & test the default user bookshelves
  .github/workflows/integration-test.yml
  prisma/seed/data/booksData.json
  prisma/seed/seeders/config.ts
  prisma/seed/seeders/review.seeder.ts
  prisma/seed/seeders/user.seeder.ts
  src/common/utils/build-default-bookshelves.ts
  src/modules/auth/auth.service.ts
  src/modules/books/books.repository.ts
  src/modules/bookshelves/bookshelves.repository.ts
  src/modules/reading-challenges/reading-challenges.repository.ts
  src/modules/reviews/reviews.repository.ts
  src/modules/users/users.repository.ts
  src/modules/users/users.service.ts
  src/tests/integration-tests/user.repository.test.ts
Labels: users:tests

#159 Adjust user seeding
  prisma/seed/seed.ts
  prisma/seed/seeders/user.seeder.ts
  src/tests/integration-tests/author.repository.test.ts
  src/tests/integration-tests/books.repository.test.ts
  src/tests/integration-tests/bookshelves.repository.test.ts
  src/tests/integration-tests/conversation.repository.test.ts
  src/tests/integration-tests/genres.repository.test.ts
  src/tests/integration-tests/reading-challenges.repository.test.ts
  src/tests/integration-tests/reviews.repository.test.ts
  src/tests/integration-tests/user.repository.test.ts
Labels: SEEDING
