Repository Eight-Horsepeople-of-the-Graduation/core, pull requests merged in 2024-06, with the labels that each got.

#74 Add swagger docs
  package.json
  requests.http
  src/app.ts
  src/prisma/migrations/20240315014158_add_unique_constraints/migration.sql
  src/prisma/migrations/20240315020514_add_user_fav_genres/migration.sql
  src/prisma/migrations/20240324220251_/migration.sql
  src/prisma/migrations/20240418235216_remove_list_and_num_of_books_from_book/migration.sql
  src/prisma/migrations/20240429203418_privacy_default/migration.sql
  src/prisma/migrations/20240502155559_/migration.sql
  src/prisma/migrations/20240502160705_/migration.sql
  src/prisma/migrations/20240502233328_20240503023320/migration.sql
  src/prisma/migrations/20240503233324_20240504023320/migration.sql
  src/prisma/migrations/20240504213055_/migration.sql
  src/prisma/migrations/20240625160640_init/migration.sql
  src/swagger/books.swagger.ts
  src/swagger/bookshelves.swagger.ts
  src/swagger/conversations.swagger.ts
  src/swagger/interfaces.ts
  src/swagger/reading-challenges.swagger.ts
  src/swagger/routes.ts
  src/swagger/swagger.json
  src/swagger/users.swagger.ts
  tsconfig.json
  tsoa.json
Labels: documentation

#79 feat(reviews): add reviews module
  src/app.ts
  src/controllers/reviews.controller.ts
  src/dtos/reviews.dto.ts
  src/loaders/express.ts
  src/prisma/migrations/20240625174440_/migration.sql
  src/repositories/reviews.repository.ts
  src/routes/reviews.route.ts
  src/services/reviews.service.ts
Labels: enhancement

#77 feat(authors & genres): Add new models for Author & Genres
  src/controllers/authors.controller.ts
  src/controllers/genres.controller.ts
  src/dtos/authors.dto.ts
  src/dtos/books.dto.ts
  src/dtos/genres.dto.ts
  src/loaders/express.ts
  src/repositories/authors.repository.ts
  src/repositories/books.repository.ts
  src/repositories/genres.repository.ts
  src/routes/authors.route.ts
  src/routes/genres.route.ts
  src/services/authors.service.ts
  src/services/books.service.ts
  src/services/genres.service.ts
Labels: enhancement

#84 refactor: change the log format
  package.json
  src/app.ts
  src/utils/logger.ts
  src/utils/prisma.ts
Labels: enhancement

#76 Integrate db with chat
  .gitignore
  package.json
  pnpm-lock.yaml
  src/config/index.ts
  src/controllers/conversations.controller.ts
  src/dtos/conversations.dto.ts
  src/routes/conversations.route.ts
  src/services/conversations.service.ts
  src/swagger/conversations.swagger.ts
  src/swagger/routes.ts
  src/swagger/swagger.json
  tsoa.json
Labels: documentation, enhancement

#86 chore: update Jest configuration and add pnpm-lock file to .gitignore
  .gitignore
  jest.config.js
  pnpm-lock.yaml
Labels: enhancement

#89 Add db container and seeding
  docker-compose.yml
  package.json
  src/dtos/users.dto.ts
  src/prisma/schema.prisma
  src/prisma/seed/data/authorsData.json
  src/prisma/seed/data/booksData.json
  src/prisma/seed/data/bookshelvesData.json
  src/prisma/seed/data/genresData.json
  src/prisma/seed/data/messagesData.json
  src/prisma/seed/data/readingChallengesData.json
  src/prisma/seed/data/reviewsData.json
  src/prisma/seed/seed.ts
  src/prisma/seed/seeders/author.seeder.ts
  src/prisma/seed/seeders/book.seeder.ts
  src/prisma/seed/seeders/bookshelf.seeder.ts
  src/prisma/seed/seeders/config.ts
  src/prisma/seed/seeders/conversation.seeder.ts
  src/prisma/seed/seeders/genre.seeder.ts
  src/prisma/seed/seeders/index.ts
  src/prisma/seed/seeders/message.seeder.ts
  src/prisma/seed/seeders/reading-challenge.seeder.ts
  src/prisma/seed/seeders/review.seeder.ts
  src/prisma/seed/seeders/user.seeder.ts
  src/prisma/seed/seeders/utils.ts
Labels: enhancement

#90 fix: rename the enum Type in the tests file
  src/tests/controllers/reading-challenges.controller.test.ts
Labels: bug
